# Generated by Django 4.1.1 on 2023-01-30 22:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=50)),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('cost', models.FloatField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_album', to='artists.artist')),
            ],
        ),
    ]
