# Generated by Django 4.1.1 on 2023-07-25 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_user'),
        ('albums', '0002_rename_datetime_album_release_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_album', to='artists.artist'),
        ),
    ]
