# Generated by Django 4.1.1 on 2023-01-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stageName', models.CharField(max_length=50, unique=True)),
                ('socialLink', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['stageName'],
            },
        ),
    ]
