# Generated by Django 4.1.1 on 2023-07-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='stageName',
        ),
    ]
